Instrumentation initial
opentracing-contrib/ruby-restclient-instrumentation pull request #1
Opened 2018-11-12 14:55 UTC by achandras

2018-11-17 01:08 UTC, mpetazzoni requested changes

2018-11-17 01:08 UTC, mpetazzoni commented on README.md
> +- `propagate_spans`: Enable propagating spans through request headers.
Rename to just `propagate`; and what you're propagating is trace context, not spans

2018-11-17 01:08 UTC, mpetazzoni commented on lib/restclient/instrumentation.rb
> +      def instrument(tracer: OpenTracing.global_tracer, propagate_spans: true)
Rename to `propagate`

2018-11-17 01:08 UTC, mpetazzoni commented on lib/restclient/instrumentation.rb
> +              @span_context = span.context
Is that thread safe?

2018-11-17 01:08 UTC, mpetazzoni commented on lib/restclient/instrumentation.rb
> +              span.set_tag("message", error.message)
This should be as a log/annotation with the `error.msg` key

2018-11-17 01:08 UTC, mpetazzoni commented on lib/restclient/instrumentation.rb
> +            OpenTracing.inject(@span_context, OpenTracing::FORMAT_RACK, req) if @span_context
Shouldn't this use B3 propagation?

2018-11-17 01:39 UTC, achandras commented on lib/restclient/instrumentation.rb
> +              @span_context = span.context
Yes, I believe so. Each request gets a new instance of this class

2018-11-17 06:16 UTC, mpetazzoni commented on lib/restclient/instrumentation.rb
> +              span.set_tag("message", error.message)
So I guess as a log event, but using the `message` key as per the spec: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#captured-errors

2018-11-19 23:14 UTC, mpetazzoni approved these changes

2018-11-19 23:14 UTC, mpetazzoni commented
I'll let @keitwb do another pass though.

2018-11-20 15:28 UTC, keitwb commented on lib/restclient/instrumentation.rb
> +            span = ::RestClient::Instrumentation.tracer.start_span("restclient.execute")
See [the note on Net::Http](https://github.com/signalfx/net-http-tracer/pull/1#discussion_r235019915).  I think we should really consider using a normalized URL, as described there, instead of a generic string for the span name.

2018-11-20 15:29 UTC, keitwb commented on lib/restclient/instrumentation.rb
> +          def execute(& block)
No space after `&`.

2018-11-20 15:35 UTC, keitwb commented on spec/instrumentation_spec.rb
> +      expect(tracer.spans.count).to be > 0
I would do some basic assertions on the span fields and also add a test for the propagation.

2018-11-20 17:22 UTC, achandras commented on lib/restclient/instrumentation.rb
> +          def execute(& block)
Is that for style consistency purposes? I was following the same style as RestClient here

2018-11-20 18:51 UTC, keitwb commented on lib/restclient/instrumentation.rb
> +          def execute(& block)
I've never seen this style in Ruby but maybe it is standard.  Look up standard Ruby style guides and see if there is any guidance.  It might be fine.

2018-11-20 19:37 UTC, achandras commented on lib/restclient/instrumentation.rb
> +          def execute(& block)
Looks like RestClient is the odd one out here. Usual style appears to be space removed

2018-11-20 21:59 UTC, rmfitzpatrick commented on README.md
> +- `propagate`: Enable propagating span contexts through request headers.
I think a saner default may be false so that users are only attempting to propagate to trusted services and not potentially misinterpreted as spamming.

2018-11-20 22:03 UTC, rmfitzpatrick commented on lib/restclient/instrumentation.rb
> +            OpenTracing.inject(@span_context, OpenTracing::FORMAT_RACK, req) if @span_context
Usually the propagation type is registered at the tracer and the format declaration (text map, binary, or http header) and carrier are established in the instrumentation.

2018-11-20 22:07 UTC, rmfitzpatrick commented on restclient-instrumentation.gemspec
> +  # end
nit: remote this and add when populated?

2018-11-20 22:19 UTC, rmfitzpatrick commented on test_app/test.rb
> +require 'jaeger/client'
Would it make sense to find a mocked mongo or use docker and modify this as an integration test w/ OpenTracingTestTracer?  Could be overkill but if this is more of a one-off span generator for collector sanity then it may not be needed for the repo.

2018-11-21 11:47 UTC, achandras commented on test_app/test.rb
> +require 'jaeger/client'
I agree that this may not be needed here. Other than a sanity check, the main gap this was filling was testing for propagation. Once I add a unit test for that, this will be unnecessary. I'll remove it or move it into the pending overall integration test with https://github.com/signalfx/signalfx-ruby-tracing.

2018-11-28 14:15 UTC, keitwb commented on README.md
> +- `propagate`: Enable propagating span contexts through request headers.
As a general rule, if a default value is debatable it is best to just make it non-default and required for the user to specify when manually instrumenting.  I think it is quite debatable since most of the OT-contrib instrumentations propagate without even giving the option of disabling the header injection.

In auto-instrumentation, it should propagate by default.

2018-11-29 18:49 UTC, keitwb approved these changes

2018-12-03 22:20 UTC, merged